{% set version = "0.1.0" %}
# {% set sha256 = "1bb7b8eafb508e16667fc246be68479110322c4cd2d0191f48bbefe25cd95cc7" %}

package:
  name: flanker
  version: {{ version }}

source:
  url: https://github.com/wtmatlock/flanker/archive/{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - flanker = flanker.flanker:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - python>=3.6
    - pip

  run:
    - python>=3.6
    - pandas>=1.2
    - biopython>=1.78
    - abricate>=1.0.1
    - mash>=2.2.2
    - networkx>=2.5

test:
  imports:
    - flanker

  commands:
    - flanker --help

about:
  home: 
  summary: 'Gene-flank analysis tool'
  license_family: MIT

extra:
  recipe-maintainers:
    - bede
    - wtmatlock
    - samlipworth
