site_name: Flanker Documentaion		

  nav:		
     - Home: README.md		
     - Clustering: clustering.md		
     - Salami mode: salami.md		
     - Multi-allelic mode: mam.md		

  theme:
     name: readthedocs
     highlightjs: true
     hljs_languages:
         - yaml
         - rust
